### ISSUE TITLE
Why is domain name relevant?

### ISSUE THREAD

**Issue by martinheidegger** [pfrazee/ctznry#2]
As far as I understand users should be able to transfer their account between servers. But if other users identify me by my user@server then a change of server could lead to confusion/loss of trust. like: Is it still the same person or is another person impersonating them?

Other decentralized systems have a "info" screen with the entire "public key" for their identity. To look up more details and see its the right one.

**Comment by pfrazee** [comment]
Two reasons:

1. We use DNS-IDs and public keys as overlapping identifiers to support both key-rotation and server rehoming (aka domain changes)
2. So that people can have global shortname user IDs

**Comment by martinheidegger** [comment]
Wouldn't a suffix showing the fi
