### ISSUE TITLE
HAL issue - base64 turns into html

### ISSUE THREAD

**Issue by StoicPacman** [pfrazee/ctznry#5]
You can paste here any base64 text and it turns into HTML in the core.

https://github.com/pfrazee/ctznry/blob/3eacfec2bd888755f2317dea7b590073ba868f1f/static/js/com/popups/edit-profile.js#L139

**Comment by pfrazee** [comment]
I've applied CSPs to the frontend and backend so that blobs should no longer get autoexec power
