### ISSUE TITLE
can't use a hyphen in roleID 

### ISSUE THREAD

**Issue by trosel** [pfrazee/ctznry#7]
On safari iOS, i can't put a hyphen in the roleID (when creating a new permission role). The example text shows that I can though.

**Comment by trosel** [comment]
I believe it's something to do with the keyup here. It strips the hyphen out after you keyup from typing it. 

https://github.com/pfrazee/ctznry/blob/0465831219c4089af8e9802c61d67b86afd1472f/static/js/com/popups/edit-role.js#L73

**Comment by pfrazee** [comment]
Fixed!

**Comment by trosel** [comment]
thanks!
